# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d5d515d91f4a8653babdfa1e622ca6d7bcbb34ed8eebe6413c9e4989f8375d27c0ed6feb5839c5bb89ca9e0c75e897319278a448f4f5c201d08a367aa1a1960

test:
  secret_key_base: 657d3ded4348ee0147fe211a123e3f531fdd69e21419ce7d965d6c0c7051da400d5d213b4162be9fe3e82bb2af8f588c829077fcdab2f15f48a350e77820620c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
